# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: fastapi_user
          POSTGRES_PASSWORD: fastapi_pass
          POSTGRES_DB: fastapi_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U fastapi_user -d fastapi_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install psql client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Create test_user in Postgres
      run: |
        PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h localhost -p 5432 -U fastapi_user -d fastapi_db -c "CREATE USER test_user WITH PASSWORD 'test_pass';"
        PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h localhost -p 5432 -U fastapi_user -d fastapi_db -c "GRANT ALL PRIVILEGES ON DATABASE fastapi_db TO test_user;"

    - name: Wait for Postgres
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 -U fastapi_user -d fastapi_db && break
          echo "Waiting for Postgres..."
          sleep 3
        done
        alembic upgrade head

    - name: Run Tests
      run: |
        pytest .
