# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ecommerce_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d ecommerce_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Postgres
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 -U postgres -d ecommerce_db && break
          echo "Waiting for Postgres..."
          sleep 3
        done
        alembic upgrade head

    - name: Run Tests
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/ecommerce_db
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pytest .
